# 동적 프로그래밍(Dynamic programming)

## 행렬 경로 문제



In [ ]:
import random
import numpy as np

class MatrixPathProblem:
    def __init__(self, matrix_size:int):
        size=matrix_size

        max_value = 20 + 1
        min_value = 3
        # 행렬 랜덤 초기화
        self.matrix = [[random.randrange(min_value, max_value) for i in range(size)] for j in range(size)];
        # 비용 행렬 초기화
        self.c = [[0 for i in range(size)] for j in range(size)];

        # n, n 까지 이르는 경로중 최대 점수
        self.CalculatePath(size -1, size -1)
        
        # 결과 출력
        self.print_result()

    def CalculatePath(self, i, j):
        pass

    def print_result(self):
        print("given matrix: ")
        print(np.matrix(self.matrix))
        print("cost matrix: ")
        print(np.matrix(self.c))

mpp = MatrixPathProblem(10)

given matrix: 
[[10  7  3  7  6 13  5 19 18 15]
 [ 3  7 16 18  4 19  3  5  7 10]
 [13 13 17  7  3 13  3 15  5 13]
 [15  3  9 13 18  3 16  7 12 10]
 [ 4 15  5 18  5 13  3 20 14 16]
 [ 8  6 16 12 11  6 19  3 18  4]
 [16  6 11 12 15 15 16 15 11  8]
 [14  3 11 13 19  7 12 20 20 13]
 [14  9  7 18 11  7  7 20 17 15]
 [ 9 10 16 17 20  7 15 19  7 14]]
cost matrix: 
[[ 10  17  20  27  33  46  51  70  88 103]
 [ 13  24  40  58  62  81  84  89  96 113]
 [ 26  39  57  65  68  94  97 112 117 130]
 [ 41  44  66  79  97 100 116 123 135 145]
 [ 45  60  71  97 102 115 119 143 157 173]
 [ 53  66  87 109 120 126 145 148 175 179]
 [ 69  75  98 121 136 151 167 182 193 201]
 [ 83  86 109 134 155 162 179 202 222 235]
 [ 97 106 116 152 166 173 186 222 239 254]
 [106 116 132 169 189 196 211 241 248 268]]


## 돌 놓기

In [ ]:
class PebbleStone:

    def __init__(self, size:int):
        self.size = size

        max_value = 20 + 1
        min_value = 3

        # 행렬 랜덤 초기화
        self.matrix = [[random.randrange(min_value, max_value) for i in range(3)] for j in range(size)];
        print(np.matrix(self.matrix))
        
        self.pattern = [[0], [1], [2], [0, 2]]

        self.compatable_p = [[1, 2], [0, 2, 3], [0, 1], [1]]

        self.peb = [[0 for i in range(4)] for j in range(size)]

        self.pebble(size)
        self.printPebbles()


    def pebble(self, n:int):
        pass


    def printPebbles(self):
        selectIdx = [-1 for _ in range(self.size)]

        # get the index of the solution
        sol_p = self.peb[self.size-1].index( max(self.peb[self.size-1]) )
        selectIdx[self.size-1] = sol_p


        for i in range(self.size-1, 1, -1):
            p = selectIdx[i]
            w = sum([ self.matrix[i][j] for j in self.pattern[p]])
            peb_cost = self.peb[i][p]
            selectIdx[i-1] = self.peb[i-1].index( peb_cost - w )


        for i in range(self.size):
            for j in range(3):
                sol_pattern = self.pattern[selectIdx[i]]
                str = "\x1b[{}m{}\x1b[0m ".format(31 if j in sol_pattern else 32, self.matrix[i][j])
                print(str, end='')
            print('')


# let's test
ps = PebbleStone(5)

[[13  6  3]
 [13 16 19]
 [ 5  3 12]
 [17  6 15]
 [15 11  5]]
[[13  6  3 16]
 [19 32 32 38]
 [37 41 44 49]
 [61 55 56 73]
 [71 84 66 75]]
13 6 3 
13 16 19 
5 3 12 
17 6 15 
15 11 5 


## 행렬의 곱셈

In [ ]:
class MathMultiply:
    def __init__(self, size:int):
        self.size = size

        max_value = 20 + 1
        min_value = 3

        self.p = [random.randrange(min_value, max_value) for _ in range(0, size+1)]
        self.m = [[0 for i in range(size)] for j in range(size)]

        print(self.p)

        self.matrixchain(size)
        
        print(np.matrix(self.m))

    def matrixchain(self, n:int):
        pass
        

mm = MathMultiply(4)

[14, 18, 15, 6, 18]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
i: 0, j: 1, r: 1
[0]
i: 1, j: 2, r: 1
[1]
i: 2, j: 3, r: 1
[2]
i: 0, j: 2, r: 2
[0, 1]
i: 1, j: 3, r: 2
[1, 2]
i: 0, j: 3, r: 3
[0, 1, 2]
[[   0 3780 1260 1512]
 [   0    0 1620 1944]
 [   0    0    0 1620]
 [   0    0    0    0]]
