# 동적 프로그래밍(Dynamic programming)

## 행렬 경로 문제



In [2]:
import random
import numpy as np

class MatrixPathProblem:
    def __init__(self, matrix_size:int):
        size=matrix_size

        max_value = 20 + 1
        min_value = 3
        # 행렬 랜덤 초기화
        self.matrix = [[random.randrange(min_value, max_value) for i in range(size)] for j in range(size)];
        # 비용 행렬 초기화
        self.c = [[0 for i in range(size)] for j in range(size)];

        # n, n 까지 이르는 경로중 최대 점수
        self.CalculatePath(size -1, size -1)
        
        # 결과 출력
        self.print_result()

    def CalculatePath(self, i, j):
        pass

    def print_result(self):
        print("given matrix: ")
        print(np.matrix(self.matrix))
        print("cost matrix: ")
        print(np.matrix(self.c))

mpp = MatrixPathProblem(10)

given matrix: 
[[20 17 13  4 15 15 20 20 20 13]
 [ 4  8 18 10  4 12 12 20  4 11]
 [18 20 13 10  7 11 10 18  7 13]
 [11 11 10 13 11  9 17 18 15 10]
 [ 4  7 17 17 10 11 15  9 12  8]
 [ 7 15  8 13  9  9  4  3 10 18]
 [11  5 17  4 20 14  5  3 17  4]
 [12 20 20  3  8  7 12  6  4  5]
 [10  5  7 19 17 18 16  4  7 12]
 [ 4 10 13 15 17  6 13 19 16 15]]
cost matrix: 
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


## 돌 놓기

In [ ]:
class PebbleStone:

    def __init__(self, size:int):
        self.size = size

        max_value = 20 + 1
        min_value = -20

        # 행렬 랜덤 초기화
        self.matrix = [[random.randrange(min_value, max_value) for i in range(3)] for j in range(size)];
        print(np.matrix(self.matrix))
        
        self.pattern = [[0], [1], [2], [0, 2]]

        self.compatable_p = [[1, 2], [0, 2, 3], [0, 1], [1]]

        self.peb = [[0 for i in range(4)] for j in range(size)]

        self.pebble(size)
        self.printPebbles()


    def pebble(self, n:int):
        pass


    def printPebbles(self):
        selectIdx = [-1 for _ in range(self.size)]

        # get the index of the solution
        sol_p = self.peb[self.size-1].index( max(self.peb[self.size-1]) )
        selectIdx[self.size-1] = sol_p


        for i in range(self.size-1, 1, -1):
            p = selectIdx[i]
            w = sum([ self.matrix[i][j] for j in self.pattern[p]])
            peb_cost = self.peb[i][p]
            selectIdx[i-1] = self.peb[i-1].index( peb_cost - w )


        for i in range(self.size):
            for j in range(3):
                sol_pattern = self.pattern[selectIdx[i]]
                str = "\x1b[{}m{}\x1b[0m ".format(31 if j in sol_pattern else 32, self.matrix[i][j])
                print(str, end='')
            print('')


# let's test
ps = PebbleStone(5)

[[13  6  3]
 [13 16 19]
 [ 5  3 12]
 [17  6 15]
 [15 11  5]]
[[13  6  3 16]
 [19 32 32 38]
 [37 41 44 49]
 [61 55 56 73]
 [71 84 66 75]]
13 6 3 
13 16 19 
5 3 12 
17 6 15 
15 11 5 


## 행렬의 곱셈

In [ ]:
class MathMultiply:
    def __init__(self, size:int):
        self.size = size

        max_value = 20 + 1
        min_value = 3

        self.p = [random.randrange(min_value, max_value) for _ in range(0, size+1)]
        self.m = [[0 for i in range(size)] for j in range(size)]

        print(self.p)

        self.matrixchain(size)

        print(np.matrix(self.m))

        self.drawParentheses()


    def matrixchain(self, n:int):
        pass

    def drawParentheses(self):
        s_paren = []
        e_paren = []

        def rParentheses(i:int, j:int):
            if( i == j ):
                return False
           
            idx = [self.m[i][k] + self.m[k+1][j] for k in range(i, j)]
            m_idx = min(idx)

            k = idx.index(m_idx) + i

            if rParentheses(i, k):
                s_paren.append(i)
                e_paren.append(k)

            if rParentheses(k+1, j):
                s_paren.append(k+1)
                e_paren.append(j)  

            return True

        rParentheses(0, self.size-1)

        result = ""
        for i in range(self.size):
            c = len([k for k in s_paren if k == i])
            for _ in range(c):
                result += "("
            result += str(i)

            c = len([k for k in e_paren if k == i])
            for _ in range(c):
                result += ")"

        print(result)



mm = MathMultiply(5)

[15, 7, 5, 10, 14, 5]
[[   0  525 1275 2275 1650]
 [   0    0  350 1190 1125]
 [   0    0    0  700  950]
 [   0    0    0    0  700]
 [   0    0    0    0    0]]
0(1(2(34)))


## LCS(최장 부분 공통 순서)

In [ ]:
import numpy as np

class LCS:
    def __init__(self, X, Y):
        self.X = X
        self.Y = Y

        self.m = len(X)
        self.n = len(Y)

        self.C = [[0 for i in range(self.n + 1)] for j in range(self.m + 1)]

        self.findLCS()

        print(np.matrix(self.C))

        self.printLCS()

    def findLCS(self): 
        # declaring the array for storing the dp values 
        """Following steps build L[m + 1][n + 1] in bottom up fashion 
        Note: L[i][j] contains length of LCS of X[0..i-1] 
        and Y[0..j-1]"""
        for i in range(self.m + 1): 
            for j in range(self.n + 1): 
                if i == 0 or j == 0 : 
                    self.C[i][j] = 0
                elif self.X[i-1] == self.Y[j-1]: 
                    self.C[i][j] = self.C[i-1][j-1]+1
                else: 
                    self.C[i][j] = max(self.C[i-1][j], self.C[i][j-1]) 
    
        # L[m][n] contains the length of LCS of X[0..n-1] & Y[0..m-1] 
        return self.C[self.m][self.n] 
    # end of function lcs 

    def printLCS(self):
        i = self.m
        j = self.n

        lcs = ''

        while( not(i == 0 or j == 0) ):

            if self.X[i-1] == self.Y[j-1]:
                lcs = self.X[i-1] + lcs
                i = i - 1
                j = j - 1
            elif self.C[i-1][j] > self.C[i][j-1]:
                i = i - 1
            else:
                j = j-1

        print(lcs)

lcs = LCS("ACGGA", "ACTG")

[[0 0 0 0 0]
 [0 1 1 1 1]
 [0 1 2 2 2]
 [0 1 2 2 3]
 [0 1 2 2 3]
 [0 1 2 2 3]]
ACG
